-- Create team_members table
create table public.team_members (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  email text not null unique,
  full_name text not null,
  role text not null default 'Team Member',
  department text not null,
  is_active boolean not null default true,
  telegram_chat_id text
);

-- Enable Row Level Security (RLS)
alter table public.team_members enable row level security;

-- Create a policy that allows anyone to read team members
create policy "Anyone can read team members"
  on public.team_members for select
  using (true);

-- Create a policy that allows authenticated users to update team members
create policy "Authenticated users can update team members"
  on public.team_members for update
  using (auth.role() = 'authenticated');

-- Add 10 hypothetical team members
insert into public.team_members (email, full_name, role, department)
values
  ('john.doe@example.com', 'John Doe', 'Admin', 'IT'),
  ('jane.smith@example.com', 'Jane Smith', 'Manager', 'Operations'),
  ('mike.johnson@example.com', 'Mike Johnson', 'Engineer', 'Development'),
  ('sarah.williams@example.com', 'Sarah Williams', 'Analyst', 'Business'),
  ('david.brown@example.com', 'David Brown', 'Engineer', 'Development'),
  ('emma.davis@example.com', 'Emma Davis', 'Manager', 'Support'),
  ('robert.wilson@example.com', 'Robert Wilson', 'Engineer', 'Development'),
  ('lisa.moore@example.com', 'Lisa Moore', 'Analyst', 'Business'),
  ('james.taylor@example.com', 'James Taylor', 'Engineer', 'Development'),
  ('patricia.anderson@example.com', 'Patricia Anderson', 'Manager', 'Operations');

-- Update all team members with the Telegram chat ID
update public.team_members
set telegram_chat_id = '811347209'
where is_active = true; 