-- Drop existing incidents table if it exists
drop table if exists public.incidents;

-- Create incidents table
create table public.incidents (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text not null,
  status text not null default 'Open',
  priority text not null default 'Medium',
  assigned_to bigint references public.team_members(id),
  resolution text,
  source text,
  client text
);

-- Enable Row Level Security (RLS)
alter table public.incidents enable row level security;

-- Create a policy that allows anyone to read incidents
create policy "Anyone can read incidents"
  on public.incidents for select
  using (true);

-- Create a policy that allows anyone to insert incidents
create policy "Anyone can insert incidents"
  on public.incidents for insert
  with check (true);

-- Create a policy that allows anyone to update incidents
create policy "Anyone can update incidents"
  on public.incidents for update
  using (true);

-- Add some sample data
insert into public.incidents (title, description, status, priority, assigned_to, resolution)
values
  ('Server Down', 'Main production server is not responding', 'Open', 'High', 1, null),
  ('Database Slow', 'Database queries are taking longer than usual', 'In Progress', 'Medium', 2, 'Increased connection pool size'),
  ('UI Bug', 'Login button not working on mobile devices', 'Closed', 'Low', 3, 'Fixed CSS media query issue'); 