-- Create comments table
create table public.comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  comment text not null
);

-- Enable Row Level Security (RLS)
alter table public.comments enable row level security;

-- Create a policy that allows anyone to read comments
create policy "Anyone can read comments"
  on public.comments for select
  using (true);

-- Create a policy that allows anyone to insert comments
create policy "Anyone can insert comments"
  on public.comments for insert
  with check (true); 