-- Drop existing analytics tables if they exist
drop table if exists public.service_health;
drop table if exists public.incident_resolutions;

-- Create service health table
create table public.service_health (
  id bigint generated by default as identity primary key,
  service_name text not null,
  status text not null default 'Operational',
  last_checked_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create incident resolutions table to track resolution details
create table public.incident_resolutions (
  id bigint generated by default as identity primary key,
  incident_id bigint references public.incidents(id),
  resolved_at timestamp with time zone default timezone('utc'::text, now()) not null,
  resolution_type text not null default 'Manual', -- 'Manual' or 'AI'
  resolution_time_minutes integer, -- Time taken to resolve
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.service_health enable row level security;
alter table public.incident_resolutions enable row level security;

-- Create policies for service_health
create policy "Anyone can read service health"
  on public.service_health for select
  using (true);

create policy "Anyone can insert service health"
  on public.service_health for insert
  with check (true);

create policy "Anyone can update service health"
  on public.service_health for update
  using (true);

-- Create policies for incident_resolutions
create policy "Anyone can read incident resolutions"
  on public.incident_resolutions for select
  using (true);

create policy "Anyone can insert incident resolutions"
  on public.incident_resolutions for insert
  with check (true);

create policy "Anyone can update incident resolutions"
  on public.incident_resolutions for update
  using (true);

-- Add sample service health data
insert into public.service_health (service_name, status)
values
  ('API Gateway', 'Operational'),
  ('Database', 'Operational'),
  ('Authentication', 'Operational'),
  ('Storage', 'Operational'),
  ('Cache', 'Operational');

-- Add sample resolution data
insert into public.incident_resolutions (incident_id, resolution_type, resolution_time_minutes)
values
  (3, 'Manual', 120),  -- For the UI Bug that was closed
  (2, 'AI', 45);       -- For the Database Slow incident 